"use client";

import { useState } from "react";

const avatars = ["MS", "AJ", "LL", "RP", "CN"];
const users = [
  ["Maya Sullivan", "maya@northstar.co", "Administrator", "Active", "Today, 09:42"],
  ["Alex Johnson", "alex.johnson@email.com", "Creator", "Active", "Yesterday, 17:20"],
  ["Lina Lee", "lina.lee@email.com", "Editor", "Active", "Sep 28, 2024"],
  ["Rafael Perez", "rafael@northstar.co", "Viewer", "Invited", "Sep 24, 2024"],
  ["Cora Nguyen", "cora.nguyen@email.com", "Creator", "Suspended", "Sep 18, 2024"],
];
const videos = [
  ["Designing for a more mindful internet", "Studio Sessions", "Published", "14.2K", "Oct 01, 2024"],
  ["How we built our community", "Yourtab Originals", "Published", "9.8K", "Sep 29, 2024"],
  ["A calmer way to stay informed", "Product Notes", "Review", "—", "Sep 28, 2024"],
  ["The creator's weekly workflow", "Studio Sessions", "Draft", "—", "Sep 26, 2024"],
];

function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) {
 return <div className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="page-description">{description}</p></div>{action}</div>;
}
function StatCard({ label, value, detail, trend, tone = "violet" }: { label: string; value: string; detail: string; trend?: string; tone?: string }) {
 return <article className="stat-card"><div className={`stat-icon ${tone}`}>✦</div><p>{label}</p><h2>{value}</h2><span className={trend ? "positive" : "muted"}>{trend && "↗ "}{trend ?? detail}</span>{trend && <small>{detail}</small>}</article>;
}
function Status({ children }: { children: string }) { return <span className={`status ${children.toLowerCase()}`}>{children}</span>; }
function ActionMenu() { return <button className="row-menu" aria-label="Open actions">•••</button>; }
function Toolbar({ placeholder = "Search" }: { placeholder?: string }) { return <div className="toolbar"><div className="search"><span>⌕</span><input placeholder={placeholder} /></div><button className="filter-button">☷ Filters <span>⌄</span></button></div>; }

export function Dashboard() { return <section className="page"><PageHeader eyebrow="OCTOBER 02, 2024" title="Good morning, Nora" description="Here’s what’s happening across Yourtab today." action={<button className="button button-primary">＋ Invite user</button>} />
 <div className="stats-grid"><StatCard label="Total users" value="12,480" trend="12.5%" detail="vs. last month"/><StatCard label="Published videos" value="1,238" trend="8.2%" detail="vs. last month" tone="pink"/><StatCard label="Active categories" value="24" detail="4 added this month" tone="blue"/><StatCard label="Pending reviews" value="18" detail="Needs your attention" tone="orange"/></div>
 <div className="dashboard-grid"><article className="panel growth-panel"><div className="panel-heading"><div><h3>Audience growth</h3><p>New member sign-ups over the last 7 days</p></div><button className="select-button">Last 7 days ⌄</button></div><div className="chart"><div className="chart-labels"><span>2k</span><span>1.5k</span><span>1k</span><span>500</span><span>0</span></div><svg viewBox="0 0 700 220" preserveAspectRatio="none" aria-label="Audience growth chart"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#7765e8" stopOpacity=".26"/><stop offset="1" stopColor="#7765e8" stopOpacity="0"/></linearGradient></defs><path d="M0 185 C45 172,58 145,100 155 S157 125,190 135 S237 92,275 112 S335 122,370 98 S424 58,463 80 S535 40,570 62 S640 28,700 40 V220 H0Z" fill="url(#fill)"/><path d="M0 185 C45 172,58 145,100 155 S157 125,190 135 S237 92,275 112 S335 122,370 98 S424 58,463 80 S535 40,570 62 S640 28,700 40" fill="none" stroke="#7161df" strokeWidth="3"/></svg><div className="chart-days"><span>Sep 26</span><span>Sep 27</span><span>Sep 28</span><span>Sep 29</span><span>Sep 30</span><span>Oct 01</span><span>Today</span></div></div></article>
 <article className="panel activity-panel"><div className="panel-heading"><div><h3>Recent activity</h3><p>The latest updates from your workspace</p></div><button className="text-button">View all</button></div>{["Maya Sullivan published a video", "Alex Johnson joined Yourtab", "A video was submitted for review"].map((item, i) => <div className="activity" key={item}><span className={`activity-icon a${i}`}>{i === 0 ? "▶" : i === 1 ? "+" : "◌"}</span><p><b>{item}</b><small>{i === 0 ? "Designing for a more mindful internet" : i === 1 ? "2 minutes ago" : "12 minutes ago"}</small></p><time>{i === 0 ? "Now" : i === 1 ? "2m" : "12m"}</time></div>)}</article></div>
 <article className="panel compact-table"><div className="panel-heading"><div><h3>Latest users</h3><p>Recently added to your workspace</p></div><button className="text-button">View users</button></div><table><thead><tr><th>USER</th><th>ROLE</th><th>JOINED</th><th></th></tr></thead><tbody>{users.slice(0,3).map((u,i) => <tr key={u[0]}><td><span className="avatar table-avatar">{avatars[i]}</span><span><b>{u[0]}</b><small>{u[1]}</small></span></td><td><Status>{u[2]}</Status></td><td>{u[4]}</td><td><ActionMenu/></td></tr>)}</tbody></table></article></section>; }

export function UsersPage() { const [form, setForm] = useState(false); return <section className="page"><PageHeader eyebrow="PEOPLE" title="Users" description="Manage the people with access to your workspace." action={<button onClick={() => setForm(!form)} className="button button-primary">＋ Invite user</button>}/>{form && <UserForm /> }<article className="panel list-panel"><Toolbar placeholder="Search users by name or email"/><table><thead><tr><th>USER</th><th>ROLE</th><th>STATUS</th><th>LAST ACTIVE</th><th></th></tr></thead><tbody>{users.map((u,i) => <tr key={u[0]}><td><span className="avatar table-avatar">{avatars[i]}</span><span><b>{u[0]}</b><small>{u[1]}</small></span></td><td>{u[2]}</td><td><Status>{u[3]}</Status></td><td>{u[4]}</td><td><ActionMenu/></td></tr>)}</tbody></table><div className="pagination">Showing <b>1–5</b> of <b>12,480</b> users <span><button>‹</button><button className="selected">1</button><button>2</button><button>3</button><button>›</button></span></div></article></section>; }
function UserForm() { return <article className="panel inline-form"><div><h3>Invite a teammate</h3><p>They’ll receive an email with instructions to join.</p></div><label>Email address<input type="email" placeholder="name@company.com" /></label><label>Role<select defaultValue="Creator"><option>Creator</option><option>Editor</option><option>Viewer</option></select></label><button className="button button-primary">Send invitation</button></article>; }

export function RolesPage() { const roles = [["Administrator","Full workspace access, including billing and settings.","2 users", "violet"],["Creator","Can create, publish, and manage their own content.","38 users", "pink"],["Editor","Can edit content and moderate comments.","19 users", "blue"],["Viewer","Can view workspace content and insights.","12,421 users", "orange"]]; return <section className="page"><PageHeader eyebrow="ACCESS CONTROL" title="Roles & permissions" description="Set clear permissions for everyone in your workspace." action={<button className="button button-primary">＋ Create role</button>}/><div className="role-grid">{roles.map(([name, desc, count, tone]) => <article className="panel role-card" key={name}><span className={`role-icon ${tone}`}>♢</span><ActionMenu/><h3>{name}</h3><p>{desc}</p><div><span className="member-stack"><i>MS</i><i>AJ</i><i>+{count.split(" ")[0]}</i></span><small>{count}</small></div><button className="text-button">Manage permissions →</button></article>)}</div><article className="panel permission-panel"><div className="panel-heading"><div><h3>Permission overview</h3><p>A quick comparison of access across roles.</p></div><button className="text-button">Edit permissions</button></div><table><thead><tr><th>PERMISSION</th><th>ADMIN</th><th>CREATOR</th><th>EDITOR</th><th>VIEWER</th></tr></thead><tbody>{["Manage workspace", "Publish videos", "Moderate comments", "View analytics"].map((p, i) => <tr key={p}><td><b>{p}</b></td>{[0,1,2,3].map((j) => <td key={j}><span className={j <= (i === 0 ? 0 : i === 1 ? 1 : i === 2 ? 2 : 3) ? "check" : "no-check"}>{j <= (i === 0 ? 0 : i === 1 ? 1 : i === 2 ? 2 : 3) ? "✓" : "—"}</span></td>)}</tr>)}</tbody></table></article></section>; }

export function VideosPage() { return <section className="page"><PageHeader eyebrow="CONTENT LIBRARY" title="Videos" description="Review, organize, and publish your video content." action={<button className="button button-primary">＋ Upload video</button>}/><div className="stats-grid stats-short"><StatCard label="All videos" value="1,238" detail="Across all statuses"/><StatCard label="Published" value="1,186" trend="96%" detail="of total videos" tone="pink"/><StatCard label="In review" value="18" detail="Awaiting decision" tone="orange"/></div><article className="panel list-panel"><Toolbar placeholder="Search videos"/><table><thead><tr><th>VIDEO</th><th>CATEGORY</th><th>STATUS</th><th>VIEWS</th><th>UPDATED</th><th></th></tr></thead><tbody>{videos.map((v,i) => <tr key={v[0]}><td><span className={`thumbnail thumb-${i}`}>▶</span><span><b>{v[0]}</b><small>{i % 2 ? "08:42 · by Maya Sullivan" : "12:18 · by Alex Johnson"}</small></span></td><td>{v[1]}</td><td><Status>{v[2]}</Status></td><td>{v[3]}</td><td>{v[4]}</td><td><ActionMenu/></td></tr>)}</tbody></table></article></section>; }
export function CategoriesPage() { const cats = [["Studio Sessions","Conversations with thoughtful creators.","184 videos","#E6E1FF"],["Yourtab Originals","Stories made by the Yourtab team.","96 videos","#FCE0EA"],["Product Notes","Updates from the team building Yourtab.","52 videos","#DDF0FF"],["Community Picks","The best videos shared by our community.","218 videos","#FFE9C9"]]; return <section className="page"><PageHeader eyebrow="CONTENT LIBRARY" title="Categories" description="Organize videos into collections your community can explore." action={<button className="button button-primary">＋ New category</button>}/><div className="category-grid">{cats.map((c) => <article className="panel category-card" key={c[0]}><div className="category-illustration" style={{background: c[3] as string}}><span>✦</span></div><ActionMenu/><h3>{c[0]}</h3><p>{c[1]}</p><footer><span>{c[2]}</span><button className="text-button">Edit →</button></footer></article>)}</div></section>; }
export function CommentsPage() { const comments = [["Lina Lee","This is such a thoughtful perspective. I’m going to share it with my team.","Designing for a more mindful internet","2 min ago","Approved"],["Jamal Woods","Would love to hear more about how you approach the research stage.","How we built our community","18 min ago","Pending"],["Cora Nguyen","Thank you for making space for this conversation!","Designing for a more mindful internet","1 hr ago","Approved"],["Elliot Park","This link might be useful to others: example.com","The creator's weekly workflow","3 hr ago","Flagged"]]; return <section className="page"><PageHeader eyebrow="COMMUNITY" title="Comments" description="Keep conversations welcoming and on-topic." action={<button className="button button-outline">⚙ Moderation settings</button>}/><div className="comment-tabs"><button className="active">All comments <span>342</span></button><button>Pending <span>18</span></button><button>Flagged <span>4</span></button></div><article className="panel comment-list"><Toolbar placeholder="Search comments"/>{comments.map((c,i) => <div className="comment" key={c[0]}><span className="avatar table-avatar">{avatars[i]}</span><div><p><b>{c[0]}</b><span> commented on </span><a>{c[2]}</a><time>{c[3]}</time></p><blockquote>{c[1]}</blockquote><div><Status>{c[4]}</Status><button className="text-button">Reply</button><button className="text-button">{c[4] === "Pending" ? "Approve" : "Hide"}</button><ActionMenu/></div></div></div>)}</article></section>; }
