"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";

export function AuthForm({ mode }: { mode: "login" | "register" }) {
 const registering = mode === "register"; const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
 async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); const data = Object.fromEntries(new FormData(event.currentTarget)); try { const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3001"}/auth/${registering ? "register" : "login"}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await res.json().catch(() => ({})); if (!res.ok) throw new Error(result.message || "Something went wrong. Please try again."); if (result.access_token) localStorage.setItem("yourtab_token", result.access_token); setMessage(registering ? "Account created! You can now start exploring." : "Welcome back! You are signed in."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to reach the service."); } finally { setLoading(false); } }
 return <form onSubmit={submit} className="mt-8 grid gap-5"><label className="grid gap-2 text-sm font-bold">Email address<input required name="email" type="email" placeholder="you@example.com" className="rounded-xl border border-zinc-300 bg-white px-4 py-3 font-normal outline-none focus:border-zinc-900"/></label>{registering && <label className="grid gap-2 text-sm font-bold">Username<input required name="username" minLength={3} placeholder="yourname" className="rounded-xl border border-zinc-300 bg-white px-4 py-3 font-normal outline-none focus:border-zinc-900"/></label>}<label className="grid gap-2 text-sm font-bold">Password<input required name="password" type="password" minLength={8} placeholder="At least 8 characters" className="rounded-xl border border-zinc-300 bg-white px-4 py-3 font-normal outline-none focus:border-zinc-900"/></label><button disabled={loading} className="rounded-xl bg-[#ff4d37] px-4 py-3 font-bold text-white disabled:opacity-60">{loading ? "Please wait..." : registering ? "Create account" : "Log in"}</button>{message && <p role="status" className="rounded-lg bg-zinc-100 p-3 text-sm text-zinc-600">{message}</p>}<p className="text-center text-sm text-zinc-500">{registering ? "Already have an account?" : "New to Yourtab?"} <Link href={registering ? "/login" : "/register"} className="font-bold text-zinc-900 underline">{registering ? "Log in" : "Create one"}</Link></p></form>;
}
