import {Body,Controller,Delete,Get,Headers,Param,Patch,Post,Query,Req,Res,UnauthorizedException,ForbiddenException} from "@nestjs/common";import {Throttle} from "@nestjs/throttler";import type {Request,Response} from "express";import {randomUUID} from "node:crypto";import {hash,compare} from "bcryptjs";import {prisma} from "@vaultstream/database";import {signAccessToken,verifyAccessToken,type AuthenticatedPrincipal} from "@vaultstream/auth";import {objectExists,presignPut,publicUrl} from "@vaultstream/storage";import Redis from "ioredis";
const redis=new Redis(process.env.REDIS_URL||"redis://localhost:6379"),cookieName="vaultstream_session";
async function auth(req:Request){const t=req.cookies?.[cookieName];if(!t)throw new UnauthorizedException();try{const token=await verifyAccessToken(t);const u=await prisma.user.findUnique({where:{id:token.id},select:{id:true,email:true,role:true,status:true}});if(!u||u.status!=="ACTIVE")throw new UnauthorizedException("Account is not active");return{id:u.id,email:u.email,role:u.role as AuthenticatedPrincipal["role"]}}catch(e){if(e instanceof UnauthorizedException)throw e;throw new UnauthorizedException("Invalid session")}}
function staff(p:AuthenticatedPrincipal){if(p.role==="USER")throw new ForbiddenException("Admin access required")}
function safeVideo(v:any){return v?{...v,views:Number(v.views||0),streamUrl:v.hlsKey?publicUrl(v.hlsKey):null}:v}\nfunction slug(s:string){return s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||randomUUID()}
@Controller("v1") export class AppController{
@Get("health")health(){return{data:{status:"ok",service:"vaultstream-api"}}}
@Post("auth/register")@Throttle({default:{limit:8,ttl:60000}})async register(@Body()b:any,@Res({passthrough:true})r:Response){if(!b.email||!b.password||b.password.length<8||!b.name)throw new UnauthorizedException("Invalid registration");const email=b.email.toLowerCase().trim();if(await prisma.user.findUnique({where:{email}}))throw new UnauthorizedException("Email already registered");const u=await prisma.user.create({data:{email,name:b.name.trim(),passwordHash:await hash(b.password,12)}});await this.session(r,u);return{data:{id:u.id,email:u.email,name:u.name,role:u.role}}}
@Post("auth/login")@Throttle({default:{limit:10,ttl:60000}})async login(@Body()b:any,@Res({passthrough:true})r:Response){const u=await prisma.user.findUnique({where:{email:b.email?.toLowerCase().trim()}});if(!u||u.status!=="ACTIVE"||!(await compare(b.password||"",u.passwordHash)))throw new UnauthorizedException("Invalid credentials");await prisma.user.update({where:{id:u.id},data:{lastLoginAt:new Date()}});await this.session(r,u);return{data:{id:u.id,email:u.email,name:u.name,role:u.role}}}
@Post("auth/logout")logout(@Res({passthrough:true})r:Response){r.clearCookie(cookieName);return{data:{ok:true}}}
@Get("auth/me")async me(@Req()q:Request){const p=await auth(q);return{data:await prisma.user.findUnique({where:{id:p.id},select:{id:true,email:true,name:true,role:true,status:true}})}}
private async session(r:Response,u:any){r.cookie(cookieName,await signAccessToken({id:u.id,email:u.email,role:u.role}),{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:15*60*1000,path:"/"})}
@Post("uploads/presign")async presign(@Req()q:Request,@Body()b:any){const p=await auth(q);if(!b.contentType?.startsWith("video/"))throw new ForbiddenException("Video only");const key=`uploads/${p.id}/${Date.now()}-${randomUUID()}-${String(b.filename).replace(/[^\w.-]/g,"_")}`;return{data:{key,url:await presignPut(key,b.contentType),expiresIn:900}}}
@Post("videos")async create(@Req()q:Request,@Body()b:any){const p=await auth(q);const sourceKey=String(b.sourceKey||"");if(!sourceKey.startsWith(`uploads/${p.id}/`))throw new ForbiddenException("Upload does not belong to this account");if(!(await objectExists(sourceKey)))throw new ForbiddenException("Upload not found");const v=await prisma.video.create({data:{ownerId:p.id,title:b.title,slug:slug(b.title)+"-"+randomUUID().slice(0,8),description:b.description,sourceKey,status:"UPLOADING",visibility:b.visibility||"PUBLIC",categories:{create:(b.categoryIds||[]).map((id:string)=>({category:{connect:{id}}}))},tags:{create:(b.tagIds||[]).map((id:string)=>({tag:{connect:{id}}}))},processingJobs:{create:{status:"QUEUED"}}}});await redis.lpush("vaultstream:video-jobs",v.id);return{data:v}}
@Get("videos")async list(@Query()q:any){const page=Math.max(1,+q.page||1),limit=Math.min(50,Math.max(1,+q.limit||20)),where:any={status:"READY",visibility:"PUBLIC"};if(q.search)where.OR=[{title:{contains:q.search,mode:"insensitive"}},{description:{contains:q.search,mode:"insensitive"}}];if(q.category)where.categories={some:{category:{slug:q.category}}};if(q.tag)where.tags={some:{tag:{slug:q.tag}}};const [items,total]=await Promise.all([prisma.video.findMany({where,orderBy:{publishedAt:"desc"},skip:(page-1)*limit,take:limit,include:{categories:{include:{category:true}},tags:{include:{tag:true}}}}),prisma.video.count({where})]);return{data:{items:items.map(safeVideo),total,page,limit}}}
@Get("videos/:id")async one(@Param("id")id:string){const v=await prisma.video.findFirst({where:{id,status:"READY",visibility:{in:["PUBLIC","UNLISTED"]}},include:{categories:{include:{category:true}},tags:{include:{tag:true}}}});if(!v)throw new UnauthorizedException("Video not found");return{data:{...safeVideo(v),streamUrl:v.hlsKey?publicUrl(v.hlsKey):null}}}
@Post("videos/:id/view")@Throttle({default:{limit:30,ttl:60000}})async view(@Param("id")id:string,@Req()q:Request,@Body()b:any){const v=await prisma.video.findFirst({where:{id,status:"READY",visibility:{in:["PUBLIC","UNLISTED"]}}});if(!v)throw new UnauthorizedException();const t=q.cookies?.[cookieName];let p:any=null;if(t)p=await verifyAccessToken(t).catch(()=>null);let shouldCount=!p;if(p){const existing=await prisma.watchHistory.findUnique({where:{userId_videoId:{userId:p.id,videoId:id}}});shouldCount=!existing;await prisma.watchHistory.upsert({where:{userId_videoId:{userId:p.id,videoId:id}},create:{userId:p.id,videoId:id,positionSec:Math.max(0,Math.floor(+b.positionSec||0))},update:{positionSec:Math.max(0,Math.floor(+b.positionSec||0)),watchedAt:new Date()}})}if(shouldCount)await prisma.video.update({where:{id},data:{views:{increment:1}}});return{data:{ok:true,viewed:shouldCount}}}
@Post("videos/:id/like")async like(@Param("id")id:string,@Req()q:Request){const p=await auth(q),e=await prisma.videoLike.findUnique({where:{userId_videoId:{userId:p.id,videoId:id}}});if(e){await prisma.videoLike.delete({where:{userId_videoId:{userId:p.id,videoId:id}}});await prisma.video.update({where:{id},data:{likesCount:{decrement:1}}});return{data:{liked:false}}}await prisma.videoLike.create({data:{userId:p.id,videoId:id}});await prisma.video.update({where:{id},data:{likesCount:{increment:1}}});return{data:{liked:true}}}
@Get("history")async history(@Req()q:Request){const p=await auth(q);const items=await prisma.watchHistory.findMany({where:{userId:p.id},orderBy:{watchedAt:"desc"},include:{video:true},take:100});return{data:items.map(x=>({...x,video:safeVideo(x.video)}))}}
@Get("categories")async cats(){return{data:await prisma.category.findMany({orderBy:{name:"asc"}})}}
@Post("categories")async addCat(@Req()q:Request,@Body()b:any){const p=await auth(q);staff(p);return{data:await prisma.category.create({data:{name:b.name,slug:slug(b.name),description:b.description}})}}
@Get("tags")async tags(){return{data:await prisma.tag.findMany({orderBy:{name:"asc"}})}}
@Post("tags")async addTag(@Req()q:Request,@Body()b:any){const p=await auth(q);staff(p);return{data:await prisma.tag.create({data:{name:b.name,slug:slug(b.name)}})}}
@Get("playlists")async pls(@Req()q:Request){const p=await auth(q);return{data:await prisma.playlist.findMany({where:{userId:p.id},include:{items:{orderBy:{position:"asc"},include:{video:true}}})}}
@Post("playlists")async newPl(@Req()q:Request,@Body()b:any){const p=await auth(q);return{data:await prisma.playlist.create({data:{userId:p.id,name:b.name,description:b.description,isPublic:!!b.isPublic}})}}
@Post("playlists/:id/items")async addPl(@Req()q:Request,@Param("id")id:string,@Body()b:any){const p=await auth(q);const l=await prisma.playlist.findFirst({where:{id,userId:p.id}});if(!l)throw new ForbiddenException();const last=await prisma.playlistItem.findFirst({where:{playlistId:id},orderBy:{position:"desc"}});return{data:await prisma.playlistItem.create({data:{playlistId:id,videoId:b.videoId,position:(last?.position??-1)+1}})}}
@Get("notifications")async notes(@Req()q:Request){const p=await auth(q);return{data:await prisma.notification.findMany({where:{userId:p.id},orderBy:{createdAt:"desc"},take:50})}}
@Patch("notifications/:id/read")async read(@Req()q:Request,@Param("id")id:string){const p=await auth(q);return{data:await prisma.notification.updateMany({where:{id,userId:p.id},data:{readAt:new Date()}})}}
@Get("ads")async ads(){return{data:await prisma.advertisement.findMany({where:{status:"ACTIVE"}})}}
@Get("admin/stats")async stats(@Req()q:Request){const p=await auth(q);staff(p);const [users,videos,views,likes]=await Promise.all([prisma.user.count(),prisma.video.count(),prisma.video.aggregate({_sum:{views:true}}),prisma.video.aggregate({_sum:{likesCount:true}})]);return{data:{users,videos,views:Number(views._sum.views||0),likes:likes._sum.likesCount||0}}}
@Get("admin/users")async users(@Req()q:Request){const p=await auth(q);staff(p);return{data:await prisma.user.findMany({select:{id:true,email:true,name:true,role:true,status:true,createdAt:true,lastLoginAt:true},orderBy:{createdAt:"desc"},take:500})}}
@Patch("admin/users/:id")async user(@Req()q:Request,@Param("id")id:string,@Body()b:any){const p=await auth(q);staff(p);if(id===p.id&&b.status==="SUSPENDED")throw new ForbiddenException("You cannot suspend yourself");if(b.role&&p.role!=="ADMIN")throw new ForbiddenException("Only admins can change roles");const data:any={};if(["ACTIVE","SUSPENDED","DELETED"].includes(b.status))data.status=b.status;if(b.role&&["USER","ADMIN","MODERATOR"].includes(b.role))data.role=b.role;if(!Object.keys(data).length)throw new ForbiddenException("No valid changes");return{data:await prisma.user.update({where:{id},data})}}
@Get("admin/videos")async av(@Req()q:Request){const p=await auth(q);staff(p);const items=await prisma.video.findMany({orderBy:{createdAt:"desc"},include:{owner:{select:{email:true,name:true}},processingJobs:true},take:500});return{data:items.map(safeVideo)}}
@Patch("admin/videos/:id")async mv(@Req()q:Request,@Param("id")id:string,@Body()b:any){const p=await auth(q);staff(p);const current=await prisma.video.findUnique({where:{id}});if(!current)throw new UnauthorizedException("Video not found");const data:any={};if(b.visibility!==undefined){if(!["PUBLIC","UNLISTED","PRIVATE"].includes(b.visibility))throw new ForbiddenException("Invalid visibility");data.visibility=b.visibility}if(b.status!==undefined){if(!["DRAFT","BLOCKED","READY"].includes(b.status))throw new ForbiddenException("Invalid admin status transition");if(b.status==="READY"&&!current.hlsKey)throw new ForbiddenException("Video is not processed yet");data.status=b.status;if(b.status==="READY"&&!current.publishedAt)data.publishedAt=new Date()}return{data:await prisma.video.update({where:{id},data})}}
@Get("admin/audit")async audit(@Req()q:Request){const p=await auth(q);staff(p);return{data:await prisma.auditLog.findMany({orderBy:{createdAt:"desc"},take:300,include:{actor:{select:{email:true,name:true}}})}}
@Post("admin/ads")async ad(@Req()q:Request,@Body()b:any){const p=await auth(q);staff(p);return{data:await prisma.advertisement.create({data:{name:b.name,type:b.type,mediaUrl:b.mediaUrl,targetUrl:b.targetUrl,status:"PAUSED"}})}}
@Patch("admin/ads/:id")async mad(@Req()q:Request,@Param("id")id:string,@Body()b:any){const p=await auth(q);staff(p);return{data:await prisma.advertisement.update({where:{id},data:{status:b.status}})}}
}