import cors from 'cors';
import express, { type Request, type Response } from 'express';
import { readCms, saveCms } from './store.js';
import type { Banner, CmsData, CustomPage, HomepageSection, SiteSettings } from './types.js';
const app = express(); const port = Number(process.env.PORT ?? 4000);
app.use(cors()); app.use(express.json({ limit: '1mb' }));
const sendError = (res: Response, message: string, status = 400) => res.status(status).json({ error: message });
const validString = (value: unknown): value is string => typeof value === 'string';
app.get('/health', (_req, res) => res.json({ status: 'ok' }));
app.get('/api/cms/public', async (_req, res) => { const cms = await readCms(); res.json({ ...cms, pages: cms.pages.filter((page) => page.published) }); });
app.get('/api/cms/settings', async (_req, res) => res.json((await readCms()).settings));
app.put('/api/cms/settings', async (req, res) => { const cms = await readCms(); const value = req.body as SiteSettings; if (!validString(value.siteName) || !validString(value.primaryColor)) return sendError(res, 'siteName and primaryColor are required.'); cms.settings = value; await saveCms(cms); res.json(cms.settings); });
app.get('/api/cms/homepage-sections', async (_req, res) => res.json((await readCms()).homepageSections));
app.put('/api/cms/homepage-sections', async (req, res) => { const sections = req.body as HomepageSection[]; if (!Array.isArray(sections) || sections.some((section) => !validString(section.id) || !validString(section.headline))) return sendError(res, 'A valid section list is required.'); const cms = await readCms(); cms.homepageSections = sections; await saveCms(cms); res.json(cms.homepageSections); });
app.get('/api/cms/banners', async (_req, res) => res.json((await readCms()).banners));
app.put('/api/cms/banners', async (req, res) => { const banners = req.body as Banner[]; if (!Array.isArray(banners) || banners.some((banner) => !validString(banner.id) || !validString(banner.title))) return sendError(res, 'A valid banner list is required.'); const cms = await readCms(); cms.banners = banners; await saveCms(cms); res.json(cms.banners); });
app.get('/api/cms/pages', async (_req, res) => res.json((await readCms()).pages));
app.get('/api/cms/pages/:slug', async (req, res) => { const page = (await readCms()).pages.find((item) => item.slug === req.params.slug); return page ? res.json(page) : sendError(res, 'Page not found.', 404); });
app.put('/api/cms/pages', async (req: Request, res: Response) => { const pages = req.body as CustomPage[]; if (!Array.isArray(pages) || pages.some((page) => !validString(page.id) || !/^[a-z0-9-]+$/.test(page.slug))) return sendError(res, 'Every page needs an id and a lowercase URL slug.'); const cms: CmsData = await readCms(); cms.pages = pages.map((page) => ({ ...page, updatedAt: new Date().toISOString() })); await saveCms(cms); res.json(cms.pages); });
app.use((error: Error, _req: Request, res: Response, _next: unknown) => { console.error(error); sendError(res, 'Unexpected server error.', 500); });
app.listen(port, () => console.log(`CMS API listening on http://localhost:${port}`));
